package co.in.oop;

public class exception3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		

		
		try {
			
			
			System.out.println("num");
			System.exit(0);
			
		}
		
//		catch (NullPointerException e){
//			
//			System.out.println("runs out of memory");
//		}
		
		finally {
			int num=12/0;
			
			System.out.println(num);
		}
//		
//  finally {
//			
//		System.out.println("erroh h");
//		}
//		
		
	}

}
