package co.in.oop;

public class exception2 {
	
	public static void main(String[] args) {
		
	
	try {
		
		System.out.println("try block");
		
	}
	
	
	catch(Exception e) {
		
		System.out.println("catch block");
	}
	
	finally {
		
		System.out.println("finally block");
		
	}
	
	
	
	
	
	}}